import { sql } from 'drizzle-orm';
import {sqliteTable, text, integer, real, index, uniqueIndex} from 'drizzle-orm/sqlite-core';

/**
 * CRA Compliance OS — relational schema.
 *
 * Conventions
 * - All ids are opaque text (`<prefix>_<nanoid>`), generated by the application.
 * - All timestamps are integer epoch **milliseconds in UTC**. The product never
 *   stores local time; rendering is localised in the UI.
 * - Every tenant-owned table carries `orgId` and must be queried with an
 *   explicit `orgId` predicate. See `src/core/tenant.ts` and the isolation test
 *   in `tests/unit/tenant-isolation.test.ts`.
 * - Money is stored in minor units (cents) as integers. Credits are integers.
 */

const now = sql`(unixepoch() * 1000)`;

// ---------------------------------------------------------------------------
// Identity & access
// ---------------------------------------------------------------------------

export const users = sqliteTable(
  'users',
  {
    id: text('id').primaryKey(),
    email: text('email').notNull(),
    emailNormalised: text('email_normalised').notNull(),
    name: text('name'),
    avatarUrl: text('avatar_url'),
    passwordHash: text('password_hash'),
    emailVerifiedAt: integer('email_verified_at'),
    isSystemAdmin: integer('is_system_admin', { mode: 'boolean' }).notNull().default(false),
    status: text('status', { enum: ['active', 'suspended', 'deleted'] })
      .notNull()
      .default('active'),
    lastLoginAt: integer('last_login_at'),
    defaultOrgId: text('default_org_id'),
    timezone: text('timezone').default('UTC'),
    locale: text('locale').default('en'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
    deletedAt: integer('deleted_at'),
  },
  (t) => [
    uniqueIndex('users_email_normalised_uq').on(t.emailNormalised),
    index('users_status_idx').on(t.status),
  ],
);

/** OAuth / external identities linked to a user (GitHub, GitLab, ...). */
export const identities = sqliteTable(
  'identities',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    provider: text('provider').notNull(),
    providerAccountId: text('provider_account_id').notNull(),
    providerLogin: text('provider_login'),
    /** Encrypted at rest with AES-256-GCM (see core/crypto.ts). Never returned by the API. */
    accessTokenEnc: text('access_token_enc'),
    refreshTokenEnc: text('refresh_token_enc'),
    tokenExpiresAt: integer('token_expires_at'),
    scope: text('scope'),
    profileJson: text('profile_json'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [uniqueIndex('identities_provider_uq').on(t.provider, t.providerAccountId), index('identities_user_idx').on(t.userId)],
);

export const sessions = sqliteTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tokenHash: text('token_hash').notNull(),
    ip: text('ip'),
    userAgent: text('user_agent'),
    expiresAt: integer('expires_at').notNull(),
    lastUsedAt: integer('last_used_at').notNull().default(now),
    revokedAt: integer('revoked_at'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [uniqueIndex('sessions_token_hash_uq').on(t.tokenHash), index('sessions_user_idx').on(t.userId), index('sessions_expires_idx').on(t.expiresAt)],
);

export const magicLinks = sqliteTable(
  'magic_links',
  {
    id: text('id').primaryKey(),
    email: text('email').notNull(),
    tokenHash: text('token_hash').notNull(),
    redirectTo: text('redirect_to'),
    expiresAt: integer('expires_at').notNull(),
    consumedAt: integer('consumed_at'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [uniqueIndex('magic_links_token_hash_uq').on(t.tokenHash), index('magic_links_email_idx').on(t.email)],
);

// ---------------------------------------------------------------------------
// Tenancy
// ---------------------------------------------------------------------------

export const organizations = sqliteTable(
  'organizations',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    /** Commercial plan key; resolves through the pricing tables. */
    planKey: text('plan_key').notNull().default('free'),
    billingEmail: text('billing_email'),
    country: text('country'),
    vatId: text('vat_id'),
    companyLegalName: text('company_legal_name'),
    /** Agency / partner model: a parent org (consultancy) managing this one. */
    parentOrgId: text('parent_org_id'),
    isAgency: integer('is_agency', { mode: 'boolean' }).notNull().default(false),
    autoTopupEnabled: integer('auto_topup_enabled', { mode: 'boolean' }).notNull().default(false),
    autoTopupThresholdCredits: integer('auto_topup_threshold_credits').notNull().default(100),
    autoTopupPackKey: text('auto_topup_pack_key'),
    retentionDays: integer('retention_days').notNull().default(365),
    currency: text('currency').notNull().default('USD'),
    seats: integer('seats').notNull().default(5),
    status: text('status', { enum: ['active', 'suspended', 'deleted'] }).notNull().default('active'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
    deletedAt: integer('deleted_at'),
  },
  (t) => [
    uniqueIndex('organizations_slug_uq').on(t.slug),
    index('organizations_parent_idx').on(t.parentOrgId),
    index('organizations_status_idx').on(t.status),
  ],
);

export const organizationMembers = sqliteTable(
  'organization_members',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: text('role', { enum: ['owner', 'admin', 'member', 'viewer'] })
      .notNull()
      .default('member'),
    invitedByUserId: text('invited_by_user_id'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [
    uniqueIndex('organization_members_uq').on(t.orgId, t.userId),
    index('organization_members_user_idx').on(t.userId),
    index('organization_members_org_role_idx').on(t.orgId, t.role),
  ],
);

export const invites = sqliteTable(
  'invites',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    role: text('role', { enum: ['owner', 'admin', 'member', 'viewer'] }).notNull(),
    tokenHash: text('token_hash').notNull(),
    invitedByUserId: text('invited_by_user_id'),
    expiresAt: integer('expires_at').notNull(),
    acceptedAt: integer('accepted_at'),
    revokedAt: integer('revoked_at'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [uniqueIndex('invites_token_hash_uq').on(t.tokenHash), index('invites_org_idx').on(t.orgId)],
);

// ---------------------------------------------------------------------------
// Source control
// ---------------------------------------------------------------------------

/** An installed GitHub App / GitLab connection owned by the organisation. */
export const integrations = sqliteTable(
  'integrations',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    provider: text('provider', { enum: ['github', 'gitlab'] }).notNull(),
    installationId: text('installation_id').notNull(),
    accountLogin: text('account_login'),
    accountType: text('account_type'),
    permissionsJson: text('permissions_json'),
    /** 'active' | 'revoked' | 'suspended' */
    status: text('status').notNull().default('active'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
    revokedAt: integer('revoked_at'),
  },
  (t) => [uniqueIndex('integrations_provider_install_uq').on(t.provider, t.installationId), index('integrations_org_idx').on(t.orgId)],
);

export const projects = sqliteTable(
  'projects',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    slug: text('slug').notNull(),
    description: text('description'),
    /** A "product" in CRA terms: the thing you place on the EU market. */
    productName: text('product_name'),
    productVersion: text('product_version'),
    supportPeriodMonths: integer('support_period_months'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
    deletedAt: integer('deleted_at'),
  },
  (t) => [uniqueIndex('projects_org_slug_uq').on(t.orgId, t.slug), index('projects_org_idx').on(t.orgId)],
);

export const repositories = sqliteTable(
  'repositories',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    projectId: text('project_id').references(() => projects.id, { onDelete: 'set null' }),
    integrationId: text('integration_id').references(() => integrations.id, { onDelete: 'set null' }),
    provider: text('provider', { enum: ['github', 'gitlab', 'upload', 'other'] })
      .notNull()
      .default('github'),
    externalId: text('external_id'),
    owner: text('owner'),
    name: text('name').notNull(),
    fullName: text('full_name'),
    defaultBranch: text('default_branch'),
    url: text('url'),
    visibility: text('visibility'),
    lastScanId: text('last_scan_id'),
    lastScanAt: integer('last_scan_at'),
    /** Content fingerprint of the dependency manifests — lets us skip no-op scans. */
    fingerprint: text('fingerprint'),
    monitoringEnabled: integer('monitoring_enabled', { mode: 'boolean' }).notNull().default(false),
    schedule: text('schedule').default('daily'),
    badgeEnabled: integer('badge_enabled', { mode: 'boolean' }).notNull().default(false),
    badgeToken: text('badge_token'),
    readinessScore: real('readiness_score'),
    openCritical: integer('open_critical').notNull().default(0),
    openHigh: integer('open_high').notNull().default(0),
    openKev: integer('open_kev').notNull().default(0),
    status: text('status', { enum: ['active', 'error', 'paused', 'deleted'] }).notNull().default('active'),
    lastError: text('last_error'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
    deletedAt: integer('deleted_at'),
  },
  (t) => [
    index('repositories_org_idx').on(t.orgId, t.status),
    index('repositories_project_idx').on(t.projectId),
    uniqueIndex('repositories_badge_token_uq').on(t.badgeToken),
  ],
);

export const scans = sqliteTable(
  'scans',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    repositoryId: text('repository_id')
      .notNull()
      .references(() => repositories.id, { onDelete: 'cascade' }),
    jobId: text('job_id'),
    trigger: text('trigger', { enum: ['manual', 'push', 'schedule', 'api', 'action', 'onboarding'] })
      .notNull()
      .default('manual'),
    ref: text('ref'),
    commitSha: text('commit_sha'),
    status: text('status', { enum: ['queued', 'running', 'succeeded', 'failed', 'cancelled', 'skipped'] })
      .notNull()
      .default('queued'),
    fingerprint: text('fingerprint'),
    skippedReason: text('skipped_reason'),
    ecosystemsJson: text('ecosystems_json'),
    manifestsJson: text('manifests_json'),
    componentCount: integer('component_count').notNull().default(0),
    vulnerabilityCount: integer('vulnerability_count').notNull().default(0),
    criticalCount: integer('critical_count').notNull().default(0),
    highCount: integer('high_count').notNull().default(0),
    mediumCount: integer('medium_count').notNull().default(0),
    lowCount: integer('low_count').notNull().default(0),
    kevCount: integer('kev_count').notNull().default(0),
    readinessScore: real('readiness_score'),
    durationMs: integer('duration_ms'),
    /** Latest human-readable progress line, so the UI never renders a fake bar. */
    progressPct: integer('progress_pct').notNull().default(0),
    progressMessage: text('progress_message'),
    creditsCharged: integer('credits_charged').notNull().default(0),
    errorCode: text('error_code'),
    errorMessage: text('error_message'),
    startedAt: integer('started_at'),
    finishedAt: integer('finished_at'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [
    index('scans_repo_idx').on(t.repositoryId, t.createdAt),
    index('scans_org_idx').on(t.orgId, t.createdAt),
    index('scans_status_idx').on(t.status),
  ],
);

// ---------------------------------------------------------------------------
// Component inventory & SBOM
// ---------------------------------------------------------------------------

export const components = sqliteTable(
  'components',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    scanId: text('scan_id')
      .notNull()
      .references(() => scans.id, { onDelete: 'cascade' }),
    repositoryId: text('repository_id').notNull(),
    name: text('name').notNull(),
    version: text('version'),
    ecosystem: text('ecosystem').notNull(),
    purl: text('purl'),
    group: text('group'),
    licensesJson: text('licenses_json'),
    scope: text('scope', { enum: ['runtime', 'development', 'unknown'] }).notNull().default('runtime'),
    /** Manifest path that declared this component, e.g. `package-lock.json`. */
    manifestPath: text('manifest_path'),
    /** True when this component is a direct (top-level) dependency. */
    isDirect: integer('is_direct', { mode: 'boolean' }).notNull().default(false),
    description: text('description'),
    homepage: text('homepage'),
    latestVersion: text('latest_version'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [
    index('components_scan_idx').on(t.scanId),
    index('components_org_repo_idx').on(t.orgId, t.repositoryId),
    index('components_purl_idx').on(t.purl),
  ],
);

export const dependencies = sqliteTable(
  'dependencies',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    scanId: text('scan_id')
      .notNull()
      .references(() => scans.id, { onDelete: 'cascade' }),
    fromComponentId: text('from_component_id').notNull(),
    toComponentId: text('to_component_id').notNull(),
    type: text('type').notNull().default('dependsOn'),
  },
  (t) => [index('dependencies_scan_idx').on(t.scanId), index('dependencies_to_idx').on(t.toComponentId)],
);

export const sboms = sqliteTable(
  'sboms',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    repositoryId: text('repository_id').notNull(),
    scanId: text('scan_id')
      .notNull()
      .references(() => scans.id, { onDelete: 'cascade' }),
    format: text('format', { enum: ['cyclonedx-json', 'cyclonedx-xml', 'spdx-json'] })
      .notNull()
      .default('cyclonedx-json'),
    specVersion: text('spec_version').notNull().default('1.6'),
    serialNumber: text('serial_number').notNull(),
    version: integer('version').notNull().default(1),
    storageKey: text('storage_key').notNull(),
    sizeBytes: integer('size_bytes').notNull().default(0),
    sha256: text('sha256').notNull(),
    componentCount: integer('component_count').notNull().default(0),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('sboms_repo_idx').on(t.repositoryId, t.createdAt), uniqueIndex('sboms_serial_uq').on(t.serialNumber)],
);

// ---------------------------------------------------------------------------
// Vulnerability intelligence
// ---------------------------------------------------------------------------

export const vulnerabilities = sqliteTable(
  'vulnerabilities',
  {
    /** Deterministic id: `<source>:<sourceId>` so ingestion is idempotent. */
    id: text('id').primaryKey(),
    source: text('source').notNull(),
    sourceId: text('source_id').notNull(),
    aliasesJson: text('aliases_json'),
    summary: text('summary'),
    details: text('details'),
    severity: text('severity', { enum: ['critical', 'high', 'medium', 'low', 'unknown'] })
      .notNull()
      .default('unknown'),
    cvssScore: real('cvss_score'),
    cvssVector: text('cvss_vector'),
    cvssVersion: text('cvss_version'),
    epssScore: real('epss_score'),
    epssPercentile: real('epss_percentile'),
    kevFlag: integer('kev_flag', { mode: 'boolean' }).notNull().default(false),
    kevDateAdded: text('kev_date_added'),
    kevDueDate: text('kev_due_date'),
    exploitMaturity: text('exploit_maturity'),
    weaknessesJson: text('weaknesses_json'),
    referencesJson: text('references_json'),
    affectedRangesJson: text('affected_ranges_json'),
    fixedVersionsJson: text('fixed_versions_json'),
    publishedAt: integer('published_at'),
    modifiedAt: integer('modified_at'),
    withdrawnAt: integer('withdrawn_at'),
    /** Raw upstream payload, for auditability and re-normalisation. */
    rawJson: text('raw_json'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [
    index('vulns_severity_idx').on(t.severity),
    index('vulns_kev_idx').on(t.kevFlag),
    index('vulns_modified_idx').on(t.modifiedAt),
  ],
);

export const componentVulnerabilities = sqliteTable(
  'component_vulnerabilities',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    scanId: text('scan_id').notNull(),
    repositoryId: text('repository_id').notNull(),
    componentId: text('component_id')
      .notNull()
      .references(() => components.id, { onDelete: 'cascade' }),
    vulnerabilityId: text('vulnerability_id')
      .notNull()
      .references(() => vulnerabilities.id, { onDelete: 'cascade' }),
    state: text('state', { enum: ['open', 'fixed', 'ignored', 'risk_accepted'] })
      .notNull()
      .default('open'),
    /** CRA Annex I / Article 14 triage fields. */
    exploitability: text('exploitability', { enum: ['none', 'poc', 'active', 'unknown'] })
      .notNull()
      .default('unknown'),
    exposure: text('exposure', { enum: ['unknown', 'internal', 'network', 'internet'] })
      .notNull()
      .default('unknown'),
    remediation: text('remediation'),
    fixedVersion: text('fixed_version'),
    /** Remediation due date derived from CRA/KEV timelines. */
    slaDueAt: integer('sla_due_at'),
    rationale: text('rationale'),
    assignedUserId: text('assigned_user_id'),
    resolvedAt: integer('resolved_at'),
    detectedAt: integer('detected_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [
    index('cv_org_state_idx').on(t.orgId, t.state),
    index('cv_repo_idx').on(t.repositoryId, t.state),
    index('cv_component_idx').on(t.componentId),
    index('cv_vuln_idx').on(t.vulnerabilityId),
    uniqueIndex('cv_scan_component_vuln_uq').on(t.scanId, t.componentId, t.vulnerabilityId),
  ],
);

// ---------------------------------------------------------------------------
// CRA compliance engine
// ---------------------------------------------------------------------------

/** Static control catalogue, seeded from the CRA requirement model. */
export const complianceControls = sqliteTable(
  'compliance_controls',
  {
    id: text('id').primaryKey(),
    domain: text('domain').notNull(),
    title: text('title').notNull(),
    description: text('description').notNull(),
    /** e.g. "Annex I Part II(1)", "Art. 13(3)", "Art. 14(2)" */
    legalRef: text('legal_ref').notNull(),
    obligation: text('obligation').notNull(),
    weight: real('weight').notNull().default(1),
    /** How the platform can satisfy this control from real data. */
    evidenceTypesJson: text('evidence_types_json').notNull(),
    applicabilityRule: text('applicability_rule').notNull().default('always'),
    remediation: text('remediation').notNull(),
    referencesJson: text('references_json'),
    /** 'automated' = machine-evaluated; 'attested' = user must supply evidence. */
    evaluation: text('evaluation', { enum: ['automated', 'attested', 'hybrid'] })
      .notNull()
      .default('automated'),
    sortOrder: integer('sort_order').notNull().default(100),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('controls_domain_idx').on(t.domain), index('controls_active_idx').on(t.isActive)],
);

export const complianceAssessments = sqliteTable(
  'compliance_assessments',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    repositoryId: text('repository_id').notNull(),
    scanId: text('scan_id'),
    controlId: text('control_id')
      .notNull()
      .references(() => complianceControls.id, { onDelete: 'cascade' }),
    status: text('status', {
      enum: ['passed', 'partial', 'missing', 'not_applicable', 'needs_review'],
    })
      .notNull()
      .default('missing'),
    /** 0..1 contribution for this control. */
    score: real('score').notNull().default(0),
    confidence: text('confidence', { enum: ['high', 'medium', 'low'] }).notNull().default('medium'),
    /** Human-readable "why is my score X" explanation. */
    rationale: text('rationale').notNull(),
    evidenceJson: text('evidence_json'),
    remediation: text('remediation'),
    ownerUserId: text('owner_user_id'),
    reviewedByUserId: text('reviewed_by_user_id'),
    reviewedAt: integer('reviewed_at'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [
    uniqueIndex('assessments_uq').on(t.orgId, t.repositoryId, t.controlId),
    index('assessments_repo_idx').on(t.repositoryId),
    index('assessments_org_status_idx').on(t.orgId, t.status),
  ],
);

// ---------------------------------------------------------------------------
// Evidence vault
// ---------------------------------------------------------------------------

export const evidence = sqliteTable(
  'evidence',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    repositoryId: text('repository_id'),
    scanId: text('scan_id'),
    type: text('type', {
      enum: ['document', 'sbom', 'scan_result', 'policy', 'remediation', 'vulnerability_record', 'report', 'audit_log', 'screenshot', 'other'],
    })
      .notNull(),
    title: text('title').notNull(),
    description: text('description'),
    storageKey: text('storage_key'),
    fileName: text('file_name'),
    mimeType: text('mime_type'),
    sizeBytes: integer('size_bytes'),
    sha256: text('sha256'),
    /** 'scan' | 'manual' | 'system' | 'api' */
    source: text('source').notNull().default('manual'),
    controlIdsJson: text('control_ids_json'),
    confidence: text('confidence', { enum: ['high', 'medium', 'low'] }).notNull().default('medium'),
    version: integer('version').notNull().default(1),
    previousEvidenceId: text('previous_evidence_id'),
    retentionUntil: integer('retention_until'),
    createdByUserId: text('created_by_user_id'),
    /** Monotonic per-org sequence; evidence rows are never mutated after insert. */
    seq: integer('seq'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [
    index('evidence_org_idx').on(t.orgId, t.createdAt),
    index('evidence_repo_idx').on(t.repositoryId),
    index('evidence_sha_idx').on(t.sha256),
  ],
);

// ---------------------------------------------------------------------------
// Reports & Article 14 incident workflow
// ---------------------------------------------------------------------------

export const reports = sqliteTable(
  'reports',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    repositoryId: text('repository_id'),
    scanId: text('scan_id'),
    kind: text('kind', { enum: ['readiness', 'findings', 'evidence_pack', 'incident', 'sbom_summary'] }).notNull(),
    title: text('title').notNull(),
    status: text('status', { enum: ['draft', 'generating', 'ready', 'failed'] }).notNull().default('draft'),
    contentJson: text('content_json'),
    storageKey: text('storage_key'),
    shareToken: text('share_token'),
    shareExpiresAt: integer('share_expires_at'),
    creditsCharged: integer('credits_charged').notNull().default(0),
    createdByUserId: text('created_by_user_id'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('reports_org_idx').on(t.orgId, t.createdAt), uniqueIndex('reports_share_token_uq').on(t.shareToken)],
);

export const incidents = sqliteTable(
  'incidents',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    repositoryId: text('repository_id'),
    componentVulnerabilityId: text('component_vulnerability_id'),
    vulnerabilityId: text('vulnerability_id'),
    title: text('title').notNull(),
    state: text('state', {
      enum: ['detected', 'triage', 'assessing', 'early_warning_drafted', 'notified', 'final_reported', 'closed'],
    })
      .notNull()
      .default('detected'),
    severity: text('severity', { enum: ['critical', 'high', 'medium', 'low', 'unknown'] }).notNull(),
    /** Clock start: when the manufacturer "became aware". Drives 24h/72h/14d. */
    awarenessAt: integer('awareness_at').notNull(),
    detectedAt: integer('detected_at').notNull(),
    earlyWarningDueAt: integer('early_warning_due_at').notNull(),
    notificationDueAt: integer('notification_due_at').notNull(),
    finalReportDueAt: integer('final_report_due_at'),
    kevFlag: integer('kev_flag', { mode: 'boolean' }).notNull().default(false),
    activelyExploited: integer('actively_exploited', { mode: 'boolean' }).notNull().default(false),
    severityRationale: text('severity_rationale'),
    affectedSummaryJson: text('affected_summary_json'),
    assigneeUserId: text('assignee_user_id'),
    createdByUserId: text('created_by_user_id'),
    closedAt: integer('closed_at'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('incidents_org_idx').on(t.orgId, t.state), index('incidents_repo_idx').on(t.repositoryId), index('incidents_due_idx').on(t.earlyWarningDueAt)],
);

export const incidentEvents = sqliteTable(
  'incident_events',
  {
    id: text('id').primaryKey(),
    incidentId: text('incident_id')
      .notNull()
      .references(() => incidents.id, { onDelete: 'cascade' }),
    orgId: text('org_id').notNull(),
    type: text('type', {
      enum: ['created', 'state_changed', 'draft_generated', 'draft_edited', 'approved', 'exported', 'note', 'closed'],
    }).notNull(),
    stage: text('stage', { enum: ['none', 'early_warning', 'notification', 'final'] })
      .notNull()
      .default('none'),
    payloadJson: text('payload_json'),
    note: text('note'),
    actorUserId: text('actor_user_id'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('incident_events_incident_idx').on(t.incidentId, t.createdAt)],
);

export const incidentReports = sqliteTable(
  'incident_reports',
  {
    id: text('id').primaryKey(),
    incidentId: text('incident_id')
      .notNull()
      .references(() => incidents.id, { onDelete: 'cascade' }),
    orgId: text('org_id').notNull(),
    stage: text('stage', { enum: ['early_warning', 'notification', 'final'] }).notNull(),
    title: text('title').notNull(),
    bodyMarkdown: text('body_markdown').notNull(),
    status: text('status', { enum: ['draft', 'in_review', 'approved', 'exported'] })
      .notNull()
      .default('draft'),
    /** 'template' (deterministic) or 'ai' (model-drafted, always traceable). */
    generatedBy: text('generated_by', { enum: ['template', 'ai', 'manual'] }).notNull().default('template'),
    /** Exact data the draft was derived from — AI outputs are always traceable. */
    sourcesJson: text('sources_json').notNull(),
    aiConfidence: text('ai_confidence'),
    aiModel: text('ai_model'),
    createdByUserId: text('created_by_user_id'),
    approvedByUserId: text('approved_by_user_id'),
    approvedAt: integer('approved_at'),
    exportedAt: integer('exported_at'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [uniqueIndex('incident_reports_uq').on(t.incidentId, t.stage), index('incident_reports_org_idx').on(t.orgId)],
);

// ---------------------------------------------------------------------------
// Credits, billing & payments
// ---------------------------------------------------------------------------

export const creditAccounts = sqliteTable(
  'credit_accounts',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    balance: integer('balance').notNull().default(0),
    lifetimePurchased: integer('lifetime_purchased').notNull().default(0),
    lifetimeGranted: integer('lifetime_granted').notNull().default(0),
    lifetimeConsumed: integer('lifetime_consumed').notNull().default(0),
    currency: text('currency').notNull().default('USD'),
    /** Bumped on every write; guards against lost updates under concurrency. */
    revision: integer('revision').notNull().default(0),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [uniqueIndex('credit_accounts_org_uq').on(t.orgId)],
);

export const creditTransactions = sqliteTable(
  'credit_transactions',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    accountId: text('account_id')
      .notNull()
      .references(() => creditAccounts.id, { onDelete: 'cascade' }),
    type: text('type', {
      enum: ['purchase', 'grant', 'promo', 'bonus', 'referral', 'reservation', 'commit', 'release', 'refund', 'expiry', 'adjustment'],
    }).notNull(),
    /** Signed: positive credits the account, negative debits it. */
    amount: integer('amount').notNull(),
    balanceAfter: integer('balance_after').notNull(),
    referenceType: text('reference_type'),
    referenceId: text('reference_id'),
    description: text('description'),
    expiresAt: integer('expires_at'),
    createdByUserId: text('created_by_user_id'),
    /** Unique per logical operation — makes all billing writes idempotent. */
    idempotencyKey: text('idempotency_key'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [
    uniqueIndex('credit_tx_idem_uq').on(t.idempotencyKey),
    index('credit_tx_account_idx').on(t.accountId, t.createdAt),
    index('credit_tx_org_idx').on(t.orgId, t.createdAt),
    index('credit_tx_ref_idx').on(t.referenceType, t.referenceId),
  ],
);

export const usageEvents = sqliteTable(
  'usage_events',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    userId: text('user_id'),
    apiKeyId: text('api_key_id'),
    /** Billable action key, resolved against `usageRules`. */
    action: text('action').notNull(),
    quantity: integer('quantity').notNull().default(1),
    credits: integer('credits').notNull().default(0),
    status: text('status', { enum: ['pending', 'committed', 'released', 'failed'] })
      .notNull()
      .default('pending'),
    resourceType: text('resource_type'),
    resourceId: text('resource_id'),
    reservationTransactionId: text('reservation_transaction_id'),
    commitTransactionId: text('commit_transaction_id'),
    metaJson: text('meta_json'),
    createdAt: integer('created_at').notNull().default(now),
    resolvedAt: integer('resolved_at'),
  },
  (t) => [index('usage_org_idx').on(t.orgId, t.createdAt), index('usage_action_idx').on(t.action), index('usage_status_idx').on(t.status)],
);

export const payments = sqliteTable(
  'payments',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    provider: text('provider', { enum: ['dodo', 'stripe', 'paddle', 'manual'] }).notNull(),
    providerPaymentId: text('provider_payment_id'),
    providerCheckoutId: text('provider_checkout_id'),
    providerCustomerId: text('provider_customer_id'),
    status: text('status', {
      enum: ['pending', 'succeeded', 'failed', 'refunded', 'disputed', 'cancelled'],
    })
      .notNull()
      .default('pending'),
    amountCents: integer('amount_cents').notNull().default(0),
    currency: text('currency').notNull().default('USD'),
    packKey: text('pack_key'),
    creditsGranted: integer('credits_granted').notNull().default(0),
    receiptUrl: text('receipt_url'),
    checkoutUrl: text('checkout_url'),
    failureReason: text('failure_reason'),
    rawJson: text('raw_json'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [
    uniqueIndex('payments_provider_id_uq').on(t.provider, t.providerPaymentId),
    index('payments_org_idx').on(t.orgId, t.createdAt),
  ],
);

export const subscriptions = sqliteTable(
  'subscriptions',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    provider: text('provider', { enum: ['dodo', 'stripe', 'paddle', 'manual'] }).notNull(),
    providerSubscriptionId: text('provider_subscription_id'),
    planKey: text('plan_key').notNull(),
    status: text('status', { enum: ['trialing', 'active', 'past_due', 'cancelled', 'paused'] }).notNull(),
    currentPeriodEnd: integer('current_period_end'),
    cancelAtPeriodEnd: integer('cancel_at_period_end', { mode: 'boolean' }).notNull().default(false),
    seats: integer('seats').notNull().default(1),
    metaJson: text('meta_json'),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('subscriptions_org_idx').on(t.orgId), index('subscriptions_status_idx').on(t.status)],
);

// ---------------------------------------------------------------------------
// Platform plumbing
// ---------------------------------------------------------------------------

export const apiKeys = sqliteTable(
  'api_keys',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    name: text('name').notNull(),
    keyPrefix: text('key_prefix').notNull(),
    keyHash: text('key_hash').notNull(),
    scopesJson: text('scopes_json').notNull(),
    lastUsedAt: integer('last_used_at'),
    expiresAt: integer('expires_at'),
    revokedAt: integer('revoked_at'),
    createdByUserId: text('created_by_user_id'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [uniqueIndex('api_keys_hash_uq').on(t.keyHash), index('api_keys_org_idx').on(t.orgId), index('api_keys_prefix_idx').on(t.keyPrefix)],
);

export const webhooks = sqliteTable(
  'webhooks',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    url: text('url').notNull(),
    secretEnc: text('secret_enc').notNull(),
    eventsJson: text('events_json').notNull(),
    isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    createdAt: integer('created_at').notNull().default(now),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('webhooks_org_idx').on(t.orgId)],
);

export const webhookDeliveries = sqliteTable(
  'webhook_deliveries',
  {
    id: text('id').primaryKey(),
    webhookId: text('webhook_id')
      .notNull()
      .references(() => webhooks.id, { onDelete: 'cascade' }),
    orgId: text('org_id').notNull(),
    eventType: text('event_type').notNull(),
    payloadJson: text('payload_json').notNull(),
    status: text('status', { enum: ['pending', 'succeeded', 'failed'] }).notNull().default('pending'),
    attempts: integer('attempts').notNull().default(0),
    responseStatus: integer('response_status'),
    lastError: text('last_error'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('webhook_deliveries_hook_idx').on(t.webhookId, t.createdAt)],
);

export const notifications = sqliteTable(
  'notifications',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    userId: text('user_id'),
    type: text('type').notNull(),
    title: text('title').notNull(),
    body: text('body'),
    linkUrl: text('link_url'),
    severity: text('severity', { enum: ['info', 'warning', 'critical'] }).notNull().default('info'),
    readAt: integer('read_at'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('notifications_user_idx').on(t.userId, t.readAt), index('notifications_org_idx').on(t.orgId, t.createdAt)],
);

export const auditLogs = sqliteTable(
  'audit_logs',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id'),
    actorUserId: text('actor_user_id'),
    actorType: text('actor_type', { enum: ['user', 'api_key', 'system', 'provider'] })
      .notNull()
      .default('user'),
    action: text('action').notNull(),
    targetType: text('target_type'),
    targetId: text('target_id'),
    metaJson: text('meta_json'),
    ip: text('ip'),
    userAgent: text('user_agent'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('audit_org_idx').on(t.orgId, t.createdAt), index('audit_action_idx').on(t.action), index('audit_target_idx').on(t.targetType, t.targetId)],
);

export const featureFlags = sqliteTable('feature_flags', {
  key: text('key').primaryKey(),
  description: text('description'),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(false),
  valueJson: text('value_json'),
  rolloutPct: integer('rollout_pct').notNull().default(100),
  updatedAt: integer('updated_at').notNull().default(now),
});

export const systemEvents = sqliteTable(
  'system_events',
  {
    id: text('id').primaryKey(),
    level: text('level', { enum: ['debug', 'info', 'warn', 'error', 'critical'] }).notNull(),
    source: text('source').notNull(),
    message: text('message').notNull(),
    metaJson: text('meta_json'),
    orgId: text('org_id'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('system_events_level_idx').on(t.level, t.createdAt), index('system_events_source_idx').on(t.source)],
);

/** Durable background job queue with retries, backoff and a dead-letter state. */
export const jobs = sqliteTable(
  'jobs',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id'),
    type: text('type').notNull(),
    payloadJson: text('payload_json').notNull(),
    status: text('status', { enum: ['pending', 'running', 'succeeded', 'failed', 'cancelled', 'dead'] })
      .notNull()
      .default('pending'),
    attempts: integer('attempts').notNull().default(0),
    maxAttempts: integer('max_attempts').notNull().default(5),
    /** Deduplication key; only one pending/running job per key at a time. */
    dedupeKey: text('dedupe_key'),
    runAt: integer('run_at').notNull().default(now),
    startedAt: integer('started_at'),
    finishedAt: integer('finished_at'),
    progressPct: integer('progress_pct').notNull().default(0),
    progressMessage: text('progress_message'),
    lastError: text('last_error'),
    resultJson: text('result_json'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [
    index('jobs_status_runat_idx').on(t.status, t.runAt),
    index('jobs_org_idx').on(t.orgId),
    index('jobs_dedupe_idx').on(t.dedupeKey),
  ],
);

export const jobEvents = sqliteTable(
  'job_events',
  {
    id: text('id').primaryKey(),
    jobId: text('job_id')
      .notNull()
      .references(() => jobs.id, { onDelete: 'cascade' }),
    orgId: text('org_id'),
    status: text('status').notNull(),
    progressPct: integer('progress_pct').notNull().default(0),
    message: text('message'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('job_events_job_idx').on(t.jobId, t.createdAt)],
);

/** Product funnel instrumentation (§49). */
export const analyticsEvents = sqliteTable(
  'analytics_events',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id'),
    userId: text('user_id'),
    anonymousId: text('anonymous_id'),
    sessionId: text('session_id'),
    name: text('name').notNull(),
    propsJson: text('props_json'),
    path: text('path'),
    referrer: text('referrer'),
    userAgent: text('user_agent'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [index('analytics_name_idx').on(t.name, t.createdAt), index('analytics_org_idx').on(t.orgId, t.createdAt), index('analytics_anon_idx').on(t.anonymousId)],
);

export const shareLinks = sqliteTable(
  'share_links',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    resourceType: text('resource_type').notNull(),
    resourceId: text('resource_id').notNull(),
    token: text('token').notNull(),
    expiresAt: integer('expires_at'),
    revokedAt: integer('revoked_at'),
    viewCount: integer('view_count').notNull().default(0),
    lastViewedAt: integer('last_viewed_at'),
    createdByUserId: text('created_by_user_id'),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [uniqueIndex('share_links_token_uq').on(t.token), index('share_links_resource_idx').on(t.resourceType, t.resourceId)],
);

export const referrals = sqliteTable(
  'referrals',
  {
    id: text('id').primaryKey(),
    orgId: text('org_id').notNull(),
    referrerUserId: text('referrer_user_id').notNull(),
    code: text('code').notNull(),
    referredOrgId: text('referred_org_id'),
    rewardCredits: integer('reward_credits').notNull().default(200),
    status: text('status', { enum: ['pending', 'converted', 'rewarded', 'cancelled'] })
      .notNull()
      .default('pending'),
    createdAt: integer('created_at').notNull().default(now),
    convertedAt: integer('converted_at'),
  },
  (t) => [uniqueIndex('referrals_code_uq').on(t.code), index('referrals_org_idx').on(t.orgId)],
);

// ---------------------------------------------------------------------------
// Commercial catalogue (§41 — pricing must never be hard-coded)
// ---------------------------------------------------------------------------

export const creditPacks = sqliteTable(
  'credit_packs',
  {
    id: text('id').primaryKey(),
    key: text('key').notNull(),
    name: text('name').notNull(),
    credits: integer('credits').notNull(),
    priceCents: integer('price_cents').notNull(),
    currency: text('currency').notNull().default('USD'),
    bonusCredits: integer('bonus_credits').notNull().default(0),
    popular: integer('popular', { mode: 'boolean' }).notNull().default(false),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    /** Product id in the payment provider's catalogue (Dodo `pdt_...`). */
    providerProductId: text('provider_product_id'),
    sortOrder: integer('sort_order').notNull().default(100),
  },
  (t) => [uniqueIndex('credit_packs_key_currency_uq').on(t.key, t.currency)],
);

export const plans = sqliteTable(
  'plans',
  {
    id: text('id').primaryKey(),
    key: text('key').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    interval: text('interval', { enum: ['month', 'year'] }).notNull().default('month'),
    priceCents: integer('price_cents').notNull(),
    currency: text('currency').notNull().default('USD'),
    creditsIncluded: integer('credits_included').notNull().default(0),
    repoLimit: integer('repo_limit').notNull().default(1),
    seatLimit: integer('seat_limit').notNull().default(3),
    featuresJson: text('features_json'),
    providerProductId: text('provider_product_id'),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    sortOrder: integer('sort_order').notNull().default(100),
  },
  (t) => [uniqueIndex('plans_key_currency_uq').on(t.key, t.currency)],
);

export const usageRules = sqliteTable(
  'usage_rules',
  {
    action: text('action').primaryKey(),
    label: text('label').notNull(),
    credits: integer('credits').notNull(),
    description: text('description'),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    updatedAt: integer('updated_at').notNull().default(now),
  },
);

export const coupons = sqliteTable(
  'coupons',
  {
    id: text('id').primaryKey(),
    code: text('code').notNull(),
    percentOff: integer('percent_off').notNull().default(0),
    bonusCredits: integer('bonus_credits').notNull().default(0),
    maxRedemptions: integer('max_redemptions'),
    redeemedCount: integer('redeemed_count').notNull().default(0),
    expiresAt: integer('expires_at'),
    active: integer('active', { mode: 'boolean' }).notNull().default(true),
    createdAt: integer('created_at').notNull().default(now),
  },
  (t) => [uniqueIndex('coupons_code_uq').on(t.code)],
);

/** Cached vulnerability-intel ingestion state (KEV / OSV / EPSS bookkeeping). */
export const intelSources = sqliteTable('intel_sources', {
  key: text('key').primaryKey(),
  lastRunAt: integer('last_run_at'),
  lastSuccessAt: integer('last_success_at'),
  lastError: text('last_error'),
  itemCount: integer('item_count').notNull().default(0),
  metaJson: text('meta_json'),
  updatedAt: integer('updated_at').notNull().default(now),
});

export const kevEntries = sqliteTable(
  'kev_entries',
  {
    cveId: text('cve_id').primaryKey(),
    vendorProject: text('vendor_project'),
    product: text('product'),
    vulnerabilityName: text('vulnerability_name'),
    dateAdded: text('date_added'),
    shortDescription: text('short_description'),
    requiredAction: text('required_action'),
    dueDate: text('due_date'),
    knownRansomware: text('known_ransomware'),
    notes: text('notes'),
    updatedAt: integer('updated_at').notNull().default(now),
  },
  (t) => [index('kev_product_idx').on(t.product)],
);

// ---------------------------------------------------------------------------
// Type exports
// ---------------------------------------------------------------------------

export type User = typeof users.$inferSelect;
export type Organization = typeof organizations.$inferSelect;
export type OrganizationMember = typeof organizationMembers.$inferSelect;
export type Repository = typeof repositories.$inferSelect;
export type Scan = typeof scans.$inferSelect;
export type Component = typeof components.$inferSelect;
export type Vulnerability = typeof vulnerabilities.$inferSelect;
export type ComponentVulnerability = typeof componentVulnerabilities.$inferSelect;
export type ComplianceControl = typeof complianceControls.$inferSelect;
export type ComplianceAssessment = typeof complianceAssessments.$inferSelect;
export type EvidenceRow = typeof evidence.$inferSelect;
export type Incident = typeof incidents.$inferSelect;
export type IncidentReport = typeof incidentReports.$inferSelect;
export type CreditAccount = typeof creditAccounts.$inferSelect;
export type CreditTransaction = typeof creditTransactions.$inferSelect;
export type UsageEvent = typeof usageEvents.$inferSelect;
export type Payment = typeof payments.$inferSelect;
export type Job = typeof jobs.$inferSelect;
export type ApiKey = typeof apiKeys.$inferSelect;
export type CreditPack = typeof creditPacks.$inferSelect;
export type Plan = typeof plans.$inferSelect;
export type UsageRule = typeof usageRules.$inferSelect;
export type KevEntry = typeof kevEntries.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
