import { Hono } from 'hono';
import { and, desc, eq } from 'drizzle-orm';
import { z } from 'zod';
import type { AppEnv } from '../core/context.js';
import { getDb } from '../db/index.js';
import {
  components as componentsTable,
  componentVulnerabilities,
  evidence,
  organizations,
  reports,
  repositories,
  scans,
  shareLinks,
  vulnerabilities,
} from '../db/schema.js';
import { newId } from '../core/ids.js';
import { AppError } from '../core/errors.js';
import { ok, created, parseBody } from '../core/http.js';
import { requireAuth, requireOrg } from '../core/auth.js';
import { audit } from '../core/audit.js';
import { env } from '../env.js';
import { buildContext, evaluate } from '../compliance/engine.js';
import { CONTROL_CATALOGUE } from '../compliance/controls.js';
import { reserveCredits } from '../modules/billing/ledger.js';
import { priorityOf, headlineFor, whyItMatters, riskScore } from './findings.js';
import { randomToken } from '../core/crypto.js';

export const reportsRoutes = new Hono<AppEnv>();

/**
 * Reports.
 *
 * A report is a **document**, not a screenshot of a dashboard: it has a title, a
 * purpose, a scope and sections that read top to bottom, and every claim in it
 * carries the evidence that supports it. Reports are stored, versioned by
 * generation time, and shareable through a revocable token.
 */

const DISCLAIMER =
  'This report is engineering evidence generated by CRA Compliance OS from repository and advisory data. It supports CRA compliance work; it is not legal advice and does not constitute a conformity assessment or CE marking.';

const createSchema = z.object({
  kind: z.enum(['readiness', 'findings', 'evidence_pack']),
  repositoryId: z.string().optional(),
  title: z.string().min(3).max(160).optional(),
});

/**
 * Evaluates either one repository or the whole organisation.
 *
 * The engine is repository-scoped by design, so an organisation-level report
 * aggregates: the score is the mean across active repositories, and each
 * control reports the *worst* status found anywhere in the estate — an
 * organisation is only as compliant as its weakest repository.
 */
function evaluateScope(orgId: string, repositoryId: string | undefined) {
  const db = getDb();

  if (repositoryId) {
    const result = evaluate(buildContext({ orgId, repositoryId }));
    return { result, repositoriesCovered: 1 };
  }

  const repos = db.select().from(repositories).where(and(eq(repositories.orgId, orgId), eq(repositories.status, 'active'))).all();
  if (repos.length === 0) {
    const result = evaluate(buildContext({ orgId, repositoryId: '' }));
    return { result, repositoriesCovered: 0 };
  }

  const perRepo = repos.map((r) => ({ repo: r, result: evaluate(buildContext({ orgId, repositoryId: r.id })) }));
  const score = Math.round(perRepo.reduce((sum, p) => sum + p.result.score, 0) / perRepo.length);
  const grade = gradeFor(score);

  const STATUS_RANK: Record<string, number> = { missing: 0, needs_review: 1, partial: 2, passed: 3, not_applicable: 4 };
  const byControl = new Map<string, { status: string; score: number; confidence: string; rationale: string; evidence: string[]; remediation: string }>();

  for (const { repo, result: r } of perRepo) {
    for (const a of r.assessments ?? []) {
      const existing = byControl.get(a.controlId);
      if (!existing) {
        byControl.set(a.controlId, { ...a });
        continue;
      }
      const rank = (s: string) => STATUS_RANK[s] ?? 5;
      if (rank(a.status) < rank(existing.status)) {
        const repoName = repo.fullName ?? repo.name ?? 'a repository';
        byControl.set(a.controlId, {
          ...a,
          rationale: `${a.rationale} (Worst result across the estate: ${repoName}.)`,
        });
      }
    }
  }

  const totals = {
    passed: [...byControl.values()].filter((a) => a.status === 'passed').length,
    partial: [...byControl.values()].filter((a) => a.status === 'partial').length,
    missing: [...byControl.values()].filter((a) => a.status === 'missing').length,
    needsReview: [...byControl.values()].filter((a) => a.status === 'needs_review').length,
    notApplicable: [...byControl.values()].filter((a) => a.status === 'not_applicable').length,
  };

  const actions = perRepo
    .flatMap(({ repo, result: r }) => (r.actions ?? []).map((a) => ({ ...a, repository: repo.fullName ?? repo.name ?? 'Repository' })))
    .sort((a, b) => b.impact - a.impact)
    .slice(0, 8);

  return {
    result: {
      score,
      grade,
      totals,
      domains: perRepo[0]?.result.domains ?? [],
      assessments: [...byControl.entries()].map(([controlId, a]) => ({ controlId, ...a })),
      actions,
    },
    repositoriesCovered: perRepo.length,
  };
}

/** The engine grades a repository; an aggregate score needs the same scale. */
function gradeFor(score: number): string {
  if (score >= 90) return 'A';
  if (score >= 75) return 'B';
  if (score >= 60) return 'C';
  if (score >= 40) return 'D';
  return 'E';
}

function actionFor(kind: string) {
  if (kind === 'readiness') return 'report.readiness' as const;
  if (kind === 'findings') return 'report.findings' as const;
  return 'report.evidence_pack' as const;
}

function defaultTitle(kind: string, scope: string) {
  const label = kind === 'readiness' ? 'CRA readiness report' : kind === 'findings' ? 'Findings report' : 'Evidence pack';
  return `${label} — ${scope}`;
}

// ---------------------------------------------------------------------------
// Report builders
// ---------------------------------------------------------------------------

interface ReportSection {
  id: string;
  heading: string;
  kind: 'prose' | 'list' | 'table' | 'metrics';
  body?: string;
  items?: Array<{ title: string; detail?: string; tone?: 'neutral' | 'warning' | 'critical' | 'good' }>;
  table?: { columns: string[]; rows: Array<Array<string | number>> };
  metrics?: Array<{ label: string; value: string; description?: string }>;
}

function buildReadinessReport(orgId: string, repositoryId: string | undefined, orgName: string) {
  const db = getDb();
  const repo = repositoryId ? db.select().from(repositories).where(eq(repositories.id, repositoryId)).get() : null;
  if (repositoryId && (!repo || repo.orgId !== orgId)) throw AppError.notFound('Repository');

  const scope = repo ? (repo.fullName ?? repo.name ?? orgName) : orgName;
  const { result } = evaluateScope(orgId, repositoryId);

  const artefacts = db
    .select()
    .from(evidence)
    .where(and(eq(evidence.orgId, orgId), ...(repositoryId ? [eq(evidence.repositoryId, repositoryId)] : [])))
    .orderBy(desc(evidence.createdAt))
    .all();

  const totals = result.totals as Record<string, number>;
  const sections: ReportSection[] = [
    {
      id: 'summary',
      heading: 'Where you stand',
      kind: 'prose',
      body:
        result.score >= 85
          ? `${scope} scores ${Math.round(result.score)} out of 100 (grade ${result.grade}). Most CRA expectations are met with evidence; the remaining work is listed below.`
          : result.score >= 60
            ? `${scope} scores ${Math.round(result.score)} out of 100 (grade ${result.grade}). The foundations are in place, but ${(totals.missing ?? 0) + (totals.needsReview ?? 0)} expectation${(totals.missing ?? 0) + (totals.needsReview ?? 0) === 1 ? '' : 's'} still need attention before this would stand up to scrutiny.`
            : `${scope} scores ${Math.round(result.score)} out of 100 (grade ${result.grade}). Significant gaps remain: start with the actions below, then re-scan to see the score move.`,
    },
    {
      id: 'metrics',
      heading: 'How the score is made up',
      kind: 'metrics',
      metrics: [
        { label: 'Readiness', value: `${Math.round(result.score)} / 100`, description: `Grade ${result.grade}` },
        { label: 'Met', value: String(totals.passed ?? 0), description: 'Controls with supporting evidence' },
        { label: 'Partially met', value: String(totals.partial ?? 0), description: 'In place but incomplete' },
        { label: 'Needs attention', value: String((totals.missing ?? 0) + (totals.needsReview ?? 0)), description: 'Gaps or unconfirmed controls' },
        { label: 'Not applicable', value: String(totals.not_applicable ?? 0) },
      ],
    },
    {
      id: 'actions',
      heading: 'What to do next',
      kind: 'list',
      items: (result.actions ?? []).slice(0, 8).map((action) => ({ title: action.title, detail: action.rationale, tone: 'warning' as const })),
    },
    {
      id: 'controls',
      heading: 'Control by control',
      kind: 'table',
      table: {
        columns: ['Expectation', 'Status', 'Why CRAOS reached this conclusion'],
        rows: result.assessments.map((a) => [controlTitle(a.controlId), humanStatus(a.status), a.rationale]),
      },
    },
  ];

  if (artefacts.length > 0) {
    sections.push({
      id: 'evidence',
      heading: 'Evidence behind this assessment',
      kind: 'table',
      table: {
        columns: ['Evidence', 'Type', 'Collected', 'Checksum'],
        rows: artefacts.slice(0, 50).map((e) => [e.title, humanEvidenceType(e.type), new Date(e.createdAt).toISOString().slice(0, 10), (e.sha256 ?? '—').slice(0, 16)]),
      },
    });
  }

  return {
    kind: 'readiness' as const,
    scope,
    score: result.score,
    grade: result.grade,
    sections,
    evidenceCount: artefacts.length,
    disclaimer: DISCLAIMER,
  };
}

function buildFindingsReport(orgId: string, repositoryId: string | undefined, orgName: string) {
  const db = getDb();
  const repo = repositoryId ? db.select().from(repositories).where(eq(repositories.id, repositoryId)).get() : null;
  if (repositoryId && (!repo || repo.orgId !== orgId)) throw AppError.notFound('Repository');
  const scope = repo ? repo.fullName ?? repo.name : orgName;

  const repoRows = repositoryId
    ? [repo!]
    : db.select().from(repositories).where(and(eq(repositories.orgId, orgId), eq(repositories.status, 'active'))).all();
  const scanIds = repoRows.map((r) => r.lastScanId).filter((id): id is string => Boolean(id));

  const links = scanIds.length
    ? db.select().from(componentVulnerabilities).where(and(eq(componentVulnerabilities.orgId, orgId))).all().filter((l) => scanIds.includes(l.scanId))
    : [];
  const comps = scanIds.length ? db.select().from(componentsTable).all().filter((c) => scanIds.includes(c.scanId)) : [];
  const vulnById = new Map(db.select().from(vulnerabilities).all().map((v) => [v.id, v]));
  const compById = new Map(comps.map((c) => [c.id, c]));
  const repoById = new Map(repoRows.map((r) => [r.id, r]));

  const rows = links
    .map((link) => ({ link, component: compById.get(link.componentId), vulnerability: vulnById.get(link.vulnerabilityId) }))
    .filter((r) => r.component && r.vulnerability)
    .map(({ link, component, vulnerability }) => ({
      state: link.state,
      priority: priorityOf({
        severity: vulnerability!.severity,
        kevFlag: vulnerability!.kevFlag,
        epssScore: vulnerability!.epssScore,
        exploitability: link.exploitability,
        exposure: link.exposure,
        state: link.state,
      }),
      severity: vulnerability!.severity,
      kevFlag: vulnerability!.kevFlag,
      text: headlineFor({
        componentName: component!.name,
        version: component!.version,
        severity: vulnerability!.severity,
        kevFlag: vulnerability!.kevFlag,
        exploitability: link.exploitability,
        repositoryName: repoById.get(link.repositoryId)?.fullName ?? 'Repository',
      }),
      why: whyItMatters({
        kevFlag: vulnerability!.kevFlag,
        epssScore: vulnerability!.epssScore,
        exploitability: link.exploitability,
        exposure: link.exposure,
        severity: vulnerability!.severity,
        state: link.state,
      }),
      fix: link.remediation ?? (link.fixedVersion ? `Upgrade ${component!.name} to ${link.fixedVersion}.` : 'No fixed version published yet'),
    }))
    .filter((r) => r.state === 'open');

  const order = { act_now: 0, prioritise: 1, monitor: 2, review: 3 } as const;
  rows.sort(
    (a, b) =>
      order[a.priority] - order[b.priority] ||
      riskScore({
        severity: b.severity,
        kevFlag: b.kevFlag,
        epssScore: null,
        exploitability: null,
        exposure: null,
      }) -
        riskScore({
          severity: a.severity,
          kevFlag: a.kevFlag,
          epssScore: null,
          exploitability: null,
          exposure: null,
        }),
  );

  const actNow = rows.filter((r) => r.priority === 'act_now');
  const prioritise = rows.filter((r) => r.priority === 'prioritise');

  const sections: ReportSection[] = [
    {
      id: 'summary',
      heading: 'Where you stand',
      kind: 'prose',
      body:
        rows.length === 0
          ? `${scope} has no open findings in the latest scans. Keep monitoring: new advisories are matched automatically.`
          : `${scope} has ${rows.length} open finding${rows.length === 1 ? '' : 's'}. ${actNow.length} need${actNow.length === 1 ? 's' : ''} action now, ${prioritise.length} should be prioritised${actNow.length === 0 && prioritise.length === 0 ? '.' : ', and the rest can follow your normal cycle.'}`,
    },
    {
      id: 'metrics',
      heading: 'At a glance',
      kind: 'metrics',
      metrics: [
        { label: 'Open findings', value: String(rows.length) },
        { label: 'Act now', value: String(actNow.length), description: 'Known exploited or actively exploited' },
        { label: 'Prioritise', value: String(prioritise.length), description: 'Critical or high severity' },
        { label: 'Repositories affected', value: String(new Set(links.map((l) => l.repositoryId)).size) },
      ],
    },
  ];

  if (actNow.length > 0) {
    sections.push({
      id: 'act-now',
      heading: 'Act now',
      kind: 'list',
      items: actNow.slice(0, 20).map((r) => ({ title: r.text, detail: `${r.why} Fix: ${r.fix}`, tone: 'critical' as const })),
    });
  }
  if (prioritise.length > 0) {
    sections.push({
      id: 'prioritise',
      heading: 'Prioritise',
      kind: 'list',
      items: prioritise.slice(0, 30).map((r) => ({ title: r.text, detail: `Fix: ${r.fix}`, tone: 'warning' as const })),
    });
  }

  sections.push({
    id: 'register',
    heading: 'Full findings register',
    kind: 'table',
    table: {
      columns: ['Finding', 'Severity', 'Recommended action'],
      rows: rows.slice(0, 200).map((r) => [r.text, humanSeverity(r.severity), r.fix]),
    },
  });

  return {
    kind: 'findings' as const,
    scope,
    sections,
    evidenceCount: 0,
    disclaimer: DISCLAIMER,
  };
}

function buildEvidencePackReport(orgId: string, repositoryId: string | undefined, orgName: string) {
  const db = getDb();
  const repo = repositoryId ? db.select().from(repositories).where(eq(repositories.id, repositoryId)).get() : null;
  if (repositoryId && (!repo || repo.orgId !== orgId)) throw AppError.notFound('Repository');
  const scope = repo ? repo.fullName ?? repo.name : orgName;

  const artefacts = db
    .select()
    .from(evidence)
    .where(and(eq(evidence.orgId, orgId), ...(repositoryId ? [eq(evidence.repositoryId, repositoryId)] : [])))
    .orderBy(desc(evidence.createdAt))
    .all();

  const { result } = evaluateScope(orgId, repositoryId);
  const scan = repo?.lastScanId ? db.select().from(scans).where(eq(scans.id, repo.lastScanId)).get() : null;

  const sections: ReportSection[] = [
    {
      id: 'summary',
      heading: 'Purpose',
      kind: 'prose',
      body: `This pack collects the evidence CRA Compliance OS holds for ${scope}. Each item is stored with a SHA-256 checksum and a timestamp, so the pack can be handed to an auditor or customer as-is.`,
    },
    {
      id: 'metrics',
      heading: 'Coverage',
      kind: 'metrics',
      metrics: [
        { label: 'Artefacts', value: String(artefacts.length) },
        { label: 'Readiness', value: `${Math.round(result.score)} / 100`, description: `Grade ${result.grade}` },
        { label: 'Components tracked', value: String(scan?.componentCount ?? 0) },
        { label: 'Last scan', value: scan?.finishedAt ? new Date(scan.finishedAt).toISOString().slice(0, 10) : 'No scan yet' },
      ],
    },
    {
      id: 'register',
      heading: 'Evidence register',
      kind: 'table',
      table: {
        columns: ['Artefact', 'Type', 'Collected', 'SHA-256'],
        rows: artefacts.map((e) => [e.title, humanEvidenceType(e.type), new Date(e.createdAt).toISOString().slice(0, 10), e.sha256 ?? '—']),
      },
    },
    {
      id: 'controls',
      heading: 'What this evidence supports',
      kind: 'table',
      table: {
        columns: ['Expectation', 'Status', 'Conclusion'],
        rows: result.assessments.map((a) => [controlTitle(a.controlId), humanStatus(a.status), a.rationale]),
      },
    },
  ];

  return {
    kind: 'evidence_pack' as const,
    scope,
    score: result.score,
    grade: result.grade,
    sections,
    evidenceCount: artefacts.length,
    disclaimer: DISCLAIMER,
  };
}

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

reportsRoutes.get('/:orgId/reports', requireAuth, requireOrg('viewer'), async (c) => {
  const orgId = c.get('orgId')!;
  const rows = getDb()
    .select()
    .from(reports)
    .where(eq(reports.orgId, orgId))
    .orderBy(desc(reports.createdAt))
    .all();

  const shares = getDb().select().from(shareLinks).where(eq(shareLinks.orgId, orgId)).all();
  const shareByResource = new Map(shares.filter((s) => !s.revokedAt).map((s) => [s.resourceId, s]));

  return ok(
    c,
    rows.map((r) => {
      const share = shareByResource.get(r.id);
      return {
        id: r.id,
        kind: r.kind,
        title: r.title,
        status: r.status,
        repositoryId: r.repositoryId,
        creditsCharged: r.creditsCharged,
        createdAt: r.createdAt,
        shared: Boolean(share),
        shareToken: share?.token ?? null,
        shareExpiresAt: share?.expiresAt ?? null,
        shareViewCount: share?.viewCount ?? 0,
      };
    }),
  );
});

reportsRoutes.get('/:orgId/reports/:reportId', requireAuth, requireOrg('viewer'), async (c) => {
  const orgId = c.get('orgId')!;
  const reportId = c.req.param('reportId');
  const row = getDb().select().from(reports).where(eq(reports.id, reportId)).get();
  if (!row || row.orgId !== orgId) throw AppError.notFound('Report');

  const share = getDb()
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.resourceId, reportId), eq(shareLinks.resourceType, 'report')))
    .get();

  const org = getDb().select().from(organizations).where(eq(organizations.id, orgId)).get();

  return ok(c, {
    id: row.id,
    kind: row.kind,
    title: row.title,
    status: row.status,
    createdAt: row.createdAt,
    repositoryId: row.repositoryId,
    creditsCharged: row.creditsCharged,
    organisation: org?.name ?? 'Organisation',
    share: share && !share.revokedAt ? { token: share.token, expiresAt: share.expiresAt, viewCount: share.viewCount, lastViewedAt: share.lastViewedAt } : null,
    content: row.contentJson ? JSON.parse(row.contentJson) : null,
  });
});

reportsRoutes.post('/:orgId/reports', requireAuth, requireOrg('member'), async (c) => {
  const orgId = c.get('orgId')!;
  const auth = c.get('auth')!;
  const body = await parseBody(c, createSchema);

  const org = getDb().select().from(organizations).where(eq(organizations.id, orgId)).get();
  const orgName = org?.name ?? 'Organisation';

  // Charge first: a report we cannot pay for is never generated.
  const reservation = reserveCredits({
    orgId,
    userId: auth.user.id,
    action: actionFor(body.kind),
    resourceType: body.repositoryId ? 'repository' : 'organization',
    resourceId: body.repositoryId ?? orgId,
    free: !env.BILLING_ENABLED,
  });

  const built =
    body.kind === 'readiness'
      ? buildReadinessReport(orgId, body.repositoryId, orgName)
      : body.kind === 'findings'
        ? buildFindingsReport(orgId, body.repositoryId, orgName)
        : buildEvidencePackReport(orgId, body.repositoryId, orgName);

  const id = newId('rep');
  const title = body.title?.trim() || defaultTitle(body.kind, built.scope);

  getDb()
    .insert(reports)
    .values({
      id,
      orgId,
      repositoryId: body.repositoryId ?? null,
      kind: body.kind,
      title,
      status: 'ready',
      contentJson: JSON.stringify({ ...built, organisation: orgName, generatedAt: Date.now() }),
      creditsCharged: reservation.credits,
      createdByUserId: auth.user.id,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    })
    .run();

  audit({
    orgId,
    action: 'report.generated',
    targetType: 'report',
    targetId: id,
    meta: { kind: body.kind, repositoryId: body.repositoryId ?? null, credits: reservation.credits },
    actorUserId: auth.user.id,
  });

  return created(c, { id, title, kind: body.kind, creditsCharged: reservation.credits });
});

const shareSchema = z.object({ expiresInDays: z.number().int().min(1).max(365).optional() });

reportsRoutes.post('/:orgId/reports/:reportId/share', requireAuth, requireOrg('admin'), async (c) => {
  const orgId = c.get('orgId')!;
  const auth = c.get('auth')!;
  const reportId = c.req.param('reportId');
  const body = await parseBody(c, shareSchema);

  const report = getDb().select().from(reports).where(eq(reports.id, reportId)).get();
  if (!report || report.orgId !== orgId) throw AppError.notFound('Report');

  const existing = getDb()
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.resourceId, reportId), eq(shareLinks.resourceType, 'report')))
    .get();

  if (existing && !existing.revokedAt) {
    return ok(c, { token: existing.token, expiresAt: existing.expiresAt, alreadyShared: true });
  }

  const token = randomToken(24);
  const expiresAt = body.expiresInDays ? Date.now() + body.expiresInDays * 86_400_000 : null;

  if (existing) {
    // Re-sharing a revoked link keeps the audit trail and revokes the old token.
    getDb()
      .update(shareLinks)
      .set({ token, expiresAt, revokedAt: null, viewCount: 0, lastViewedAt: null, createdAt: Date.now(), createdByUserId: auth.user.id })
      .where(eq(shareLinks.id, existing.id))
      .run();
  } else {
    getDb()
      .insert(shareLinks)
      .values({
        id: newId('shr'),
        orgId,
        resourceType: 'report',
        resourceId: reportId,
        token,
        expiresAt,
        createdByUserId: auth.user.id,
        createdAt: Date.now(),
      })
      .run();
  }

  audit({ orgId, action: 'report.shared', targetType: 'report', targetId: reportId, meta: { expiresAt }, actorUserId: auth.user.id });

  return created(c, { token, expiresAt, url: `/share/${token}` });
});

reportsRoutes.delete('/:orgId/reports/:reportId/share', requireAuth, requireOrg('admin'), async (c) => {
  const orgId = c.get('orgId')!;
  const auth = c.get('auth')!;
  const reportId = c.req.param('reportId');

  const share = getDb()
    .select()
    .from(shareLinks)
    .where(and(eq(shareLinks.resourceId, reportId), eq(shareLinks.resourceType, 'report')))
    .get();
  if (!share || share.orgId !== orgId) throw AppError.notFound('Share link');

  getDb().update(shareLinks).set({ revokedAt: Date.now() }).where(eq(shareLinks.id, share.id)).run();
  audit({ orgId, action: 'report.share_revoked', targetType: 'report', targetId: reportId, actorUserId: auth.user.id });

  return ok(c, { revoked: true });
});

reportsRoutes.delete('/:orgId/reports/:reportId', requireAuth, requireOrg('admin'), async (c) => {
  const orgId = c.get('orgId')!;
  const reportId = c.req.param('reportId');
  const report = getDb().select().from(reports).where(eq(reports.id, reportId)).get();
  if (!report || report.orgId !== orgId) throw AppError.notFound('Report');

  getDb().delete(shareLinks).where(eq(shareLinks.resourceId, reportId)).run();
  getDb().delete(reports).where(eq(reports.id, reportId)).run();
  audit({ orgId, action: 'report.deleted', targetType: 'report', targetId: reportId });

  return ok(c, { deleted: true });
});

// ---------------------------------------------------------------------------
// Wording helpers — reports are read by people, not by machines.
// ---------------------------------------------------------------------------

/** Control titles live in the catalogue, so reports read as English, not IDs. */
function controlTitle(controlId: string): string {
  return CONTROL_CATALOGUE.find((c) => c.id === controlId)?.title ?? controlId;
}

function humanStatus(status: string): string {
  return (
    {
      passed: 'Met',
      partial: 'Partially met',
      missing: 'Needs attention',
      needs_review: 'Needs confirmation',
      not_applicable: 'Not applicable',
    } as Record<string, string>
  )[status] ?? status;
}

function humanSeverity(severity: string | null): string {
  return (
    { critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low', unknown: 'Unrated' } as Record<string, string>
  )[severity ?? 'unknown'] ?? 'Unrated';
}

function humanEvidenceType(type: string): string {
  return (
    {
      document: 'Policy or procedure',
      remediation: 'Remediation record',
      report: 'Test or audit report',
      sbom: 'Software inventory (SBOM)',
      scan: 'Scan result',
      incident: 'Incident record',
      other: 'Other',
    } as Record<string, string>
  )[type] ?? type;
}

export { humanStatus, humanSeverity, humanEvidenceType };
